name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
    - '*'
    tags:
    - '*'
jobs:
  macos:
    runs-on: macos-latest
    - name: Install Dependencies
      run: |
        rm -f /usr/local/bin/2to3*
        rm -f /usr/local/bin/idle3*
        rm -f /usr/local/bin/pydoc3*
        rm -f /usr/local/bin/python3*
        brew install --force boost lcov llvm
    - name: Check
      run: |
        llvm-cov --version
